[main]
font=JetBrainsMono Nerd Font:size=11
prompt="❯ "
icon-theme=Papirus-Dark
icons-enabled=yes
width=30
lines=10
horizontal-pad=25
vertical-pad=15
inner-pad=10
line-height=30
border-width=2
border-radius=15

[colors]
# خلفية سوداء شفافة
background=000000dd
text=ffffffff
match=89ddffff
selection=222222ff
selection-text=ffffffff
selection-match=89ddffff
# لون الحدود بنفسجي
border=bb9af7ff
